<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { nanoid } from 'nanoid'
import { useConversationStore } from '@/stores/conversation-store'
import { useModelStore } from '@/stores/model-store'
import { useSessionStore } from '@/stores/session-store'
import { useMetricsStore } from '@/stores/metrics-store'
import { useOllamaStream } from '@/composables/useOllamaStream'
import { useRagStore } from '@/stores/rag-store'
import { findCommand } from '@/services/slash-command-registry'
import { useToolWorkshopStore } from '@/stores/tool-workshop-store'
import { useMemoryStore } from '@/stores/memory-store'
import { useTokenStore } from '@/stores/token-store'
import { useQualityStore } from '@/stores/quality-store'
import { analyzeResponseQuality } from '@/services/quality-analyzer'
import { prepareContext, embedNewMessages } from '@/services/context-manager'
import { conversationDB } from '@/services/conversation-db'
import type { SlashCommandContext } from '@/types/slash-command'
import ChatMessageList from './ChatMessageList.vue'
import ChatInput from './ChatInput.vue'
import type { ChatSettings } from '@/types/conversation'
import type { ChatAttachment } from '@/types/attachment'
import ChatSettingsPanel from './ChatSettingsPanel.vue'
import ModelCapabilityIcons from '@/components/common/ModelCapabilityIcons.vue'
import { useI18n } from 'vue-i18n'
import { ChevronDown, Pencil, X, Clock, Settings, Download } from 'lucide-vue-next'

const { t } = useI18n()

const router = useRouter()
const conversationStore = useConversationStore()
const modelStore = useModelStore()
const sessionStore = useSessionStore()
const ragStore = useRagStore()
const metricsStore = useMetricsStore()
const toolWorkshopStore = useToolWorkshopStore()
const memoryStore = useMemoryStore()
const tokenStore = useTokenStore()
const qualityStore = useQualityStore()
const { isStreaming, currentSessionId, startChatStream, cancel } = useOllamaStream()

const selectedModel = ref('')
const modelDropdownOpen = ref(false)
function closeDropdownDelayed() {
  setTimeout(() => { modelDropdownOpen.value = false }, 150)
}
const ragEnabled = ref(true)
const showSettings = ref(false)
const showHistory = ref(false)
const showExportMenu = ref(false)

function handleExportJson() {
  const conv = conversation.value
  if (!conv || conv.messages.length === 0) return
  const content = JSON.stringify(conv.messages, null, 2)
  const blob = new Blob([content], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `chat-${conv.id}.json`
  a.click()
  URL.revokeObjectURL(url)
  showExportMenu.value = false
}

function handleExportMarkdown() {
  const conv = conversation.value
  if (!conv || conv.messages.length === 0) return
  const lines = conv.messages.map((m) => {
    const role = m.role.charAt(0).toUpperCase() + m.role.slice(1)
    const time = new Date(m.timestamp).toLocaleString()
    return `### ${role}\n*${time}*\n\n${m.content}`
  })
  const md = `# Chat Export — ${conv.name}\n\n${lines.join('\n\n---\n\n')}\n\n---\n*Generated by LLMxRay — Local LLM Observatory*\n`
  const blob = new Blob([md], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `chat-${conv.id}.md`
  a.click()
  URL.revokeObjectURL(url)
  showExportMenu.value = false
}

function handleExportText() {
  const conv = conversation.value
  if (!conv || conv.messages.length === 0) return
  const content = conv.messages
    .map((m) => `[${m.role}] ${m.content}`)
    .join('\n\n')
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `chat-${conv.id}.txt`
  a.click()
  URL.revokeObjectURL(url)
  showExportMenu.value = false
}

// History panel state
const historyEditingId = ref<string | null>(null)
const historyEditName = ref('')

function selectConversation(id: string) {
  conversationStore.setActiveConversation(id)
}

function startHistoryRename(id: string, currentName: string) {
  historyEditingId.value = id
  historyEditName.value = currentName
}

function commitHistoryRename(id: string) {
  const trimmed = historyEditName.value.trim()
  if (trimmed) {
    conversationStore.renameConversation(id, trimmed)
  }
  historyEditingId.value = null
}

function cancelHistoryRename() {
  historyEditingId.value = null
}

function handleHistoryRenameKeydown(e: KeyboardEvent, id: string) {
  if (e.key === 'Enter') commitHistoryRename(id)
  else if (e.key === 'Escape') cancelHistoryRename()
}

function formatRelativeDate(timestamp: number): string {
  const now = Date.now()
  const diff = now - timestamp
  const minutes = Math.floor(diff / 60_000)
  if (minutes < 1) return t('common.time.justNow')
  if (minutes < 60) return t('dashboard.conversation.minutesAgo', { n: minutes })
  const hours = Math.floor(minutes / 60)
  if (hours < 24) return t('dashboard.conversation.hoursAgo', { n: hours })
  const days = Math.floor(hours / 24)
  if (days < 7) return t('dashboard.conversation.daysAgo', { n: days })
  return new Date(timestamp).toLocaleDateString()
}
const chatSettings = ref<ChatSettings>({
  systemPrompt: '',
  options: {},
})
const notificationMessage = ref<string | null>(null)
let notificationTimer: ReturnType<typeof setTimeout> | null = null

const conversation = computed(() => conversationStore.activeConversation)
const messages = computed(() => conversation.value?.messages ?? [])

const isVision = computed(() => modelStore.isVisionModel(selectedModel.value))

const sessionError = computed(() => {
  const sid = latestSessionId.value ?? currentSessionId.value
  if (!sid) return null
  const session = sessionStore.sessionById(sid)
  if (session?.status === 'error' && session.error) return session.error
  return null
})

/** Derive the latest session ID from conversation messages so it survives navigation. */
const latestSessionId = computed(() => {
  const msgs = messages.value
  for (let i = msgs.length - 1; i >= 0; i--) {
    if (msgs[i]!.sessionId) return msgs[i]!.sessionId
  }
  return null
})

// Pending name for conversations not yet created (pre-chat naming)
const pendingName = ref(t('dashboard.conversation.untitled'))
const editingName = ref(false)
const editNameValue = ref('')

/** The display name — from the active conversation, or the pending name if none exists yet */
const displayName = computed(() => conversation.value?.name ?? pendingName.value)

function startEditName() {
  editNameValue.value = displayName.value
  editingName.value = true
}

function commitEditName() {
  const trimmed = editNameValue.value.trim()
  if (!trimmed) {
    editingName.value = false
    return
  }
  if (conversation.value) {
    conversationStore.renameConversation(conversation.value.id, trimmed)
  } else {
    pendingName.value = trimmed
  }
  editingName.value = false
}

function cancelEditName() {
  editingName.value = false
}

function handleNameKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter') commitEditName()
  else if (e.key === 'Escape') cancelEditName()
}

onMounted(async () => {
  await modelStore.fetchModels()
  if (modelStore.chatModelNames.length > 0 && !selectedModel.value) {
    selectedModel.value = modelStore.chatModelNames[0]!
  }
  await ragStore.loadDocuments()
})

// Apply model-specific defaults when model changes
watch(selectedModel, (name) => {
  if (!name) return
  const defaults = modelStore.getModelDefaults(name)
  if (Object.keys(defaults).length > 0) {
    chatSettings.value = {
      systemPrompt: chatSettings.value.systemPrompt,
      options: { ...defaults },
    }
  }
})

// Restore sessions and tokens from IDB when switching to a persisted conversation
watch(
  () => conversationStore.activeConversationId,
  async (convId) => {
    if (!convId) return
    const conv = conversationStore.conversations.get(convId)
    if (!conv) return

    // Update model selector to match conversation's model
    if (conv.model && modelStore.chatModelNames.includes(conv.model)) {
      selectedModel.value = conv.model
    }

    // Restore sessions from IDB into session store
    try {
      const storedSessions = await conversationDB.getSessionsByConversation(convId)
      for (const stored of storedSessions) {
        if (!sessionStore.sessionById(stored.id)) {
          sessionStore.sessions.set(stored.id, {
            id: stored.id,
            mode: stored.mode,
            model: stored.model,
            status: stored.status,
            createdAt: stored.createdAt,
            prompt: stored.prompt,
            messages: stored.messages,
            options: stored.options,
            outputText: stored.outputText,
            metrics: stored.metrics,
            error: stored.error,
            doneReason: stored.doneReason,
          })
          sessionStore.linkSessionToConversation(stored.id, convId)
        }
        // Restore tokens from IDB
        await tokenStore.loadTokens(stored.id)
      }
    } catch (e) {
      console.error('Failed to restore sessions for conversation:', e)
    }
  },
)

async function handleSend(text: string, attachments: ChatAttachment[] = []) {
  if (!selectedModel.value) return

  // Create conversation on first message (not eagerly)
  let convId = conversationStore.activeConversationId
  if (!convId) {
    convId = conversationStore.createConversation(selectedModel.value)
    // Apply pending name if user set one before chatting
    if (pendingName.value !== t('dashboard.conversation.untitled')) {
      conversationStore.renameConversation(convId, pendingName.value)
    }
    pendingName.value = t('dashboard.conversation.untitled')
  }
  // Update the conversation's model if user changed it
  const conv0 = conversationStore.conversations.get(convId)
  if (conv0 && conv0.model !== selectedModel.value) {
    conv0.model = selectedModel.value
  }

  // Build content with document attachments prepended
  const docAttachments = attachments.filter((a) => a.type === 'document' && a.content)
  const imageAttachments = attachments.filter((a) => a.type === 'image' && a.content)

  let content = text
  if (docAttachments.length > 0) {
    const docContext = docAttachments
      .map((a) => `[Attached: ${a.name}]\n${a.content}`)
      .join('\n\n')
    content = docContext + '\n\n---\n\n' + text
  }

  // Add user message
  const userMsg = {
    id: nanoid(),
    conversationId: convId,
    role: 'user' as const,
    content,
    timestamp: Date.now(),
    isStreaming: false,
    attachments: attachments.length > 0 ? attachments : undefined,
  }
  conversationStore.addMessage(convId, userMsg)

  // Create assistant placeholder
  const assistantMsgId = nanoid()
  const assistantMsg = {
    id: assistantMsgId,
    conversationId: convId,
    role: 'assistant' as const,
    content: '',
    timestamp: Date.now(),
    isStreaming: true,
  }
  conversationStore.addMessage(convId, assistantMsg)

  // Get messages in Ollama format and start chat stream
  const ollamaMessages = conversationStore.getMessagesAsOllamaFormat(convId)
  // Remove the empty assistant message we just added for display
  const messagesToSend = ollamaMessages.slice(0, -1)

  // Inject images into the last user message for multimodal models
  if (imageAttachments.length > 0) {
    const lastUserMsg = [...messagesToSend].reverse().find((m) => m.role === 'user')
    if (lastUserMsg) {
      lastUserMsg.images = imageAttachments
        .map((a) => a.content!.replace(/^data:[^;]+;base64,/, ''))
    }
  }

  // Inject system prompt if set
  if (chatSettings.value.systemPrompt.trim()) {
    messagesToSend.unshift({
      role: 'system',
      content: chatSettings.value.systemPrompt.trim(),
    })
  }

  // Inject RAG context if enabled and documents are available
  if (ragEnabled.value && ragStore.enabledDocuments.length > 0) {
    try {
      const ragContext = await ragStore.getContextForQuery(
        text,
        selectedModel.value,
        5,
      )
      if (ragContext) {
        messagesToSend.unshift({
          role: 'system',
          content: ragContext,
        })
      }
    } catch {
      // RAG context injection failed silently — continue without it
    }
  }

  // Apply memory context manager (sliding window, summarization, facts, RAG memory)
  let finalMessages = messagesToSend
  try {
    const existingSummary = memoryStore.getSummary(convId)?.summary
    const result = await prepareContext({
      conversationId: convId,
      messages: messagesToSend,
      model: selectedModel.value,
      settings: memoryStore.settings,
      userFactsPrompt: memoryStore.getFactsAsSystemPrompt(),
      existingSummary,
    })
    finalMessages = result.messages
    if (result.newSummary) {
      const nonSystem = messagesToSend.filter((m) => m.role !== 'system')
      memoryStore.setSummary(convId, result.newSummary, nonSystem.length)
    }
  } catch {
    // Context preparation failed — send raw messages
  }

  try {
    // Merge conversation options with settings panel options
    const mergedOptions = {
      ...conversation.value?.options,
      ...chatSettings.value.options,
    }
    const enabledTools = toolWorkshopStore.enabledDefinitions
    const sessionId = await startChatStream(
      selectedModel.value,
      finalMessages,
      mergedOptions,
      enabledTools.length > 0 ? enabledTools : undefined,
    )

    // Link the assistant message to the session
    const conv = conversationStore.conversations.get(convId)
    const msg = conv?.messages.find((m) => m.id === assistantMsgId)
    if (msg) msg.sessionId = sessionId

    // Link session to conversation for IDB persistence
    sessionStore.linkSessionToConversation(sessionId, convId)

    // Watch for session output updates
    const stopWatch = watch(
      () => sessionStore.sessionById(sessionId)?.outputText,
      (outputText) => {
        if (outputText !== undefined) {
          conversationStore.updateAssistantContent(convId!, assistantMsgId, outputText)
        }
      },
    )

    // Watch for completion — embed messages for RAG memory
    const capturedConvId = convId
    const capturedText = text
    const stopStatusWatch = watch(
      () => sessionStore.sessionById(sessionId)?.status,
      (status) => {
        if (status === 'completed' || status === 'error' || status === 'cancelled') {
          conversationStore.finalizeMessage(capturedConvId, assistantMsgId)
          isStreaming.value = false
          stopWatch()
          stopStatusWatch()

          // Persist token array to IndexedDB for diagnostic replay
          tokenStore.persistTokens(sessionId)

          // Run quality analysis on completed assistant response
          if (status === 'completed') {
            const session = sessionStore.sessionById(sessionId)
            const assistantContent = session?.outputText ?? ''
            const displayText = assistantContent.replace(/<think>[\s\S]*?<\/think>/g, '').trim()
            const metrics = metricsStore.getMetrics(sessionId)
            const report = analyzeResponseQuality(
              assistantMsgId,
              sessionId,
              displayText,
              metrics?.completionTokenCount ?? 0,
              chatSettings.value.options.num_predict as number | undefined,
              session?.doneReason,
            )
            qualityStore.setReport(assistantMsgId, report)
          }

          // Embed user + assistant messages for RAG-based message memory (fire and forget)
          if (
            status === 'completed' &&
            memoryStore.settings.ragMemory.enabled &&
            memoryStore.settings.ragMemory.embeddingModel
          ) {
            const assistantContent = sessionStore.sessionById(sessionId)?.outputText ?? ''
            embedNewMessages(
              capturedConvId,
              [
                { role: 'user', content: capturedText, timestamp: userMsg.timestamp },
                { role: 'assistant', content: assistantContent, timestamp: Date.now() },
              ],
              memoryStore.settings.ragMemory.embeddingModel,
            ).catch(() => {
              // Embedding failed silently
            })
          }
        }
      },
    )
  } catch {
    conversationStore.finalizeMessage(convId, assistantMsgId)
  }
}

function handleCancel() {
  cancel()
}

function startNewChat() {
  conversationStore.setActiveConversation(null)
  pendingName.value = t('dashboard.conversation.untitled')
}

function openSession(sessionId: string) {
  router.push({ name: 'session', params: { id: sessionId } })
}

function showNotification(msg: string) {
  notificationMessage.value = msg
  if (notificationTimer) clearTimeout(notificationTimer)
  notificationTimer = setTimeout(() => {
    notificationMessage.value = null
  }, 5000)
}

function dismissNotification() {
  notificationMessage.value = null
  if (notificationTimer) clearTimeout(notificationTimer)
}

const defaultSettings: ChatSettings = {
  systemPrompt: '',
  options: {},
}

async function handleCommand(name: string, args: string) {
  const cmd = findCommand(name)
  if (!cmd) {
    showNotification(`Unknown command: /${name}. Type /help for available commands.`)
    return
  }

  const ctx: SlashCommandContext = {
    clearConversation: () => conversationStore.setActiveConversation(null),
    newChat: () => conversationStore.setActiveConversation(null),
    sendAsUser: (text: string) => handleSend(text),
    copyLastResponse: () => {
      const assistantMsgs = messages.value.filter((m) => m.role === 'assistant')
      const last = assistantMsgs[assistantMsgs.length - 1]
      if (last?.content) {
        navigator.clipboard.writeText(last.content)
        showNotification('Copied to clipboard.')
      } else {
        showNotification('No assistant response to copy.')
      }
    },
    exportConversation: (format: 'json' | 'text') => {
      const conv = conversation.value
      if (!conv || conv.messages.length === 0) {
        showNotification('No conversation to export.')
        return
      }
      let content: string
      let filename: string
      if (format === 'json') {
        content = JSON.stringify(conv.messages, null, 2)
        filename = `chat-${conv.id}.json`
      } else {
        content = conv.messages
          .map((m) => `[${m.role}] ${m.content}`)
          .join('\n\n')
        filename = `chat-${conv.id}.txt`
      }
      const blob = new Blob([content], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = filename
      a.click()
      URL.revokeObjectURL(url)
    },
    setSystemPrompt: (prompt: string) => {
      chatSettings.value = { ...chatSettings.value, systemPrompt: prompt }
    },
    setOption: (key, value) => {
      chatSettings.value = {
        ...chatSettings.value,
        options: { ...chatSettings.value.options, [key]: value },
      }
    },
    resetSettings: () => {
      chatSettings.value = { ...defaultSettings }
    },
    setJsonFormat: (_enabled: boolean) => {
      // Ollama format option is on the request, not chatSettings.options
      // For now, show notification
      showNotification('JSON format toggled. This affects the next request.')
    },
    switchModel: (name: string) => {
      selectedModel.value = name
    },
    availableModels: modelStore.chatModelNames,
    currentModel: selectedModel.value,
    toggleRag: () => {
      ragEnabled.value = !ragEnabled.value
    },
    ragEnabled: ragEnabled.value,
    navigate: (path: string) => router.push(path),
    openSettings: () => {
      showSettings.value = true
    },
    openSessionDetails: () => {
      const sid = latestSessionId.value
      if (sid) {
        router.push({ name: 'session', params: { id: sid } })
      } else {
        showNotification('No active session.')
      }
    },
    addFact: (content: string) => memoryStore.addFact(content),
    removeFact: (search: string) => memoryStore.removeFactByContent(search),
    getFacts: () => memoryStore.facts,
    showNotification,
    messages: messages.value,
    chatSettings,
    currentSessionId: latestSessionId.value ?? currentSessionId.value,
    getSessionTokenCount: () => {
      const sid = latestSessionId.value ?? currentSessionId.value
      if (!sid) return null
      const metrics = metricsStore.getMetrics(sid)
      if (!metrics) return null
      return { prompt: metrics.promptTokenCount, completion: metrics.completionTokenCount }
    },
    getAverageSpeed: () => {
      const agg = metricsStore.aggregate
      return agg.totalSessions > 0 ? agg.avgTps : null
    },
    getOllamaStatus: async () => {
      try {
        const res = await fetch('/api/tags')
        return { connected: res.ok, model: selectedModel.value }
      } catch {
        return { connected: false, model: selectedModel.value }
      }
    },
  }

  await cmd.execute(args, ctx)
}
</script>

<template>
  <div class="flex h-full flex-col">
    <!-- Command notification toast -->
    <Transition
      enter-active-class="transition-all duration-200 ease-out"
      enter-from-class="opacity-0 -translate-y-2"
      leave-active-class="transition-all duration-150 ease-in"
      leave-to-class="opacity-0 -translate-y-2"
    >
      <div
        v-if="notificationMessage"
        class="absolute left-1/2 top-16 z-50 -translate-x-1/2 rounded-xl border border-border-default bg-surface-raised px-4 py-3 shadow-lg"
      >
        <div class="flex items-start gap-3">
          <p class="max-w-md whitespace-pre-wrap text-sm text-text-primary">{{ notificationMessage }}</p>
          <button
            class="shrink-0 text-text-muted hover:text-text-primary transition-colors text-xs"
            aria-label="Dismiss notification"
            @click="dismissNotification"
          >
            ✕
          </button>
        </div>
      </div>
    </Transition>

    <!-- Top bar with model selector + new chat -->
    <div class="flex items-center justify-between border-b border-border-default bg-surface-raised px-4 py-2">
      <div class="flex items-center gap-3">
        <div class="relative">
          <button
            class="flex items-center gap-2 rounded-lg border border-border-default bg-surface px-3 py-1.5 text-sm text-text-primary outline-none hover:border-accent/50 focus:border-accent"
            @click="modelDropdownOpen = !modelDropdownOpen"
            @blur="closeDropdownDelayed"
          >
            <span v-if="!selectedModel" class="text-text-muted">{{ $t('common.model.noModels') }}</span>
            <template v-else>
              <span>{{ selectedModel }}</span>
              <ModelCapabilityIcons :model-name="selectedModel" />
            </template>
            <ChevronDown class="h-3 w-3 text-text-muted transition-transform" :class="modelDropdownOpen ? 'rotate-180' : ''" />
          </button>
          <div
            v-if="modelDropdownOpen"
            class="absolute left-0 top-full z-50 mt-1 max-h-64 w-max min-w-full overflow-y-auto rounded-lg border border-border-default bg-surface-raised shadow-lg"
          >
            <button
              v-for="name in modelStore.chatModelNames"
              :key="name"
              class="flex w-full items-center gap-2 px-3 py-1.5 text-start text-sm transition-colors"
              :class="name === selectedModel ? 'bg-accent/10 text-accent' : 'text-text-primary hover:bg-surface-overlay'"
              @mousedown.prevent="selectedModel = name; modelDropdownOpen = false"
            >
              <span>{{ name }}</span>
              <ModelCapabilityIcons :model-name="name" />
            </button>
          </div>
        </div>
        <div v-if="editingName" class="flex items-center">
          <input
            v-model="editNameValue"
            class="w-48 rounded border border-accent bg-surface px-2 py-0.5 text-xs text-text-primary outline-none"
            @blur="commitEditName"
            @keydown="handleNameKeydown"
            @vue:mounted="($event: any) => { $event.el.focus(); $event.el.select() }"
          />
        </div>
        <button
          v-else
          class="flex items-center gap-1 rounded px-1.5 py-0.5 text-xs text-text-muted hover:text-text-primary hover:bg-surface-overlay transition-colors truncate max-w-[200px]"
          :title="$t('dashboard.conversation.clickToRename')"
          @click="startEditName"
        >
          <span class="truncate">{{ displayName }}</span>
          <Pencil class="h-2.5 w-2.5 shrink-0 opacity-0 group-hover:opacity-100" />
        </button>
      </div>
      <div class="flex items-center gap-2">
        <button
          v-if="latestSessionId"
          class="rounded-lg px-3 py-1.5 text-xs text-accent hover:bg-surface-overlay transition-colors"
          @click="openSession(latestSessionId!)"
        >
          {{ $t('dashboard.conversation.viewSessionDetails') }}
        </button>
        <button
          class="flex items-center gap-1 rounded-lg px-3 py-1.5 text-xs transition-colors"
          :class="showHistory ? 'bg-accent/10 text-accent' : 'text-text-secondary hover:bg-surface-overlay hover:text-text-primary'"
          @click="showHistory = !showHistory"
        >
          <Clock class="h-3.5 w-3.5" />
          <span>{{ $t('dashboard.conversation.history') }}</span>
        </button>
        <!-- Export dropdown -->
        <div class="relative">
          <button
            class="flex items-center gap-1 rounded-lg px-3 py-1.5 text-xs transition-colors"
            :class="showExportMenu ? 'bg-accent/10 text-accent' : 'text-text-secondary hover:bg-surface-overlay hover:text-text-primary'"
            @click="showExportMenu = !showExportMenu"
          >
            <Download class="h-3.5 w-3.5" />
            <span>{{ $t('common.actions.export') }}</span>
          </button>
          <div v-if="showExportMenu" class="fixed inset-0 z-10" @click="showExportMenu = false" />
          <div
            v-if="showExportMenu"
            class="absolute end-0 top-full z-20 mt-1 w-48 rounded-lg border border-border-default bg-surface-raised shadow-lg py-1"
          >
            <button class="w-full px-3 py-2 text-start text-xs text-text-secondary hover:bg-surface-overlay" @click="handleExportJson">
              {{ $t('dashboard.export.downloadJson') }}
            </button>
            <button class="w-full px-3 py-2 text-start text-xs text-text-secondary hover:bg-surface-overlay" @click="handleExportMarkdown">
              {{ $t('dashboard.export.downloadMarkdown') }}
            </button>
            <button class="w-full px-3 py-2 text-start text-xs text-text-secondary hover:bg-surface-overlay" @click="handleExportText">
              {{ $t('dashboard.export.downloadText') }}
            </button>
          </div>
        </div>
        <button
          class="rounded-lg px-3 py-1.5 text-xs text-text-secondary hover:bg-surface-overlay hover:text-text-primary transition-colors"
          @click="startNewChat"
        >
          {{ $t('dashboard.conversation.newChatButton') }}
        </button>
        <button
          class="flex items-center gap-1 rounded-lg px-3 py-1.5 text-xs transition-colors"
          :class="showSettings ? 'bg-accent/10 text-accent' : 'text-text-secondary hover:bg-surface-overlay hover:text-text-primary'"
          @click="showSettings = !showSettings"
        >
          <Settings class="h-3.5 w-3.5" />
          <span>{{ $t('dashboard.settings.chatSettings') }}</span>
        </button>
      </div>
    </div>

    <!-- Main content area: history + messages + settings -->
    <div class="flex flex-1 min-h-0">
      <!-- History side panel -->
      <div
        v-if="showHistory"
        class="w-64 shrink-0 border-e border-border-default bg-surface-raised flex flex-col"
      >
        <div class="flex items-center justify-between border-b border-border-default px-4 py-2">
          <span class="text-xs font-medium text-text-secondary">{{ $t('dashboard.conversation.chatHistory') }}</span>
          <button
            class="text-text-muted hover:text-text-primary transition-colors text-xs"
            aria-label="Close history"
            @click="showHistory = false"
          >
            ✕
          </button>
        </div>
        <div class="flex-1 overflow-y-auto p-2">
          <p
            v-if="conversationStore.recentConversations.length === 0"
            class="px-2 py-4 text-[10px] text-text-muted italic text-center"
          >
            {{ $t('dashboard.conversation.noConversationsYet') }}
          </p>
          <div v-else class="space-y-0.5">
            <div
              v-for="conv in conversationStore.recentConversations"
              :key="conv.id"
              class="group flex items-center gap-1 rounded-lg px-2.5 py-2 text-xs transition-colors cursor-pointer"
              :class="
                conv.id === conversationStore.activeConversationId
                  ? 'bg-surface-overlay text-accent'
                  : 'text-text-secondary hover:bg-surface-overlay hover:text-text-primary'
              "
              @click="selectConversation(conv.id)"
            >
              <div v-if="historyEditingId === conv.id" class="flex-1 min-w-0">
                <input
                  v-model="historyEditName"
                  class="w-full rounded bg-surface px-1.5 py-0.5 text-xs text-text-primary outline-none border border-accent"
                  @blur="commitHistoryRename(conv.id)"
                  @keydown="handleHistoryRenameKeydown($event, conv.id)"
                  @vue:mounted="($event: any) => { $event.el.focus(); $event.el.select() }"
                />
              </div>
              <template v-else>
                <div class="flex-1 min-w-0">
                  <p class="truncate text-[11px]">{{ conv.name }}</p>
                  <p class="truncate text-[9px] text-text-muted">
                    {{ conv.model }} · {{ formatRelativeDate(conv.updatedAt) }}
                  </p>
                </div>
                <div class="hidden shrink-0 items-center gap-0.5 group-hover:flex">
                  <button
                    class="rounded p-0.5 text-text-muted hover:text-text-primary transition-colors"
                    :title="$t('dashboard.conversation.rename')"
                    @click.stop="startHistoryRename(conv.id, conv.name)"
                  >
                    <Pencil class="h-3 w-3" />
                  </button>
                  <button
                    class="rounded p-0.5 text-text-muted hover:text-error transition-colors"
                    :title="$t('common.actions.delete')"
                    @click.stop="conversationStore.deleteConversation(conv.id)"
                  >
                    <X class="h-3 w-3" />
                  </button>
                </div>
              </template>
            </div>
          </div>
        </div>
      </div>

      <!-- Chat column -->
      <div class="flex flex-1 flex-col min-w-0">
        <!-- Error banner -->
        <div
          v-if="sessionError"
          class="mx-4 mt-2 rounded-lg border border-error/30 bg-error/10 px-4 py-2.5 text-sm text-error"
        >
          <span class="font-medium">{{ $t('common.status.error') }}:</span> {{ sessionError }}
        </div>
        <ChatMessageList :messages="messages" />
        <ChatInput
          :is-streaming="isStreaming"
          :selected-model="selectedModel"
          :is-vision-model="isVision"
          @send="handleSend"
          @command="handleCommand"
          @cancel="handleCancel"
        />
      </div>

      <!-- Settings side panel -->
      <div
        v-if="showSettings"
        class="w-72 shrink-0 border-s border-border-default bg-surface-raised"
      >
        <div class="flex items-center justify-between border-b border-border-default px-4 py-2">
          <span class="text-xs font-medium text-text-secondary">{{ $t('dashboard.settings.chatSettings') }}</span>
          <button
            class="text-text-muted hover:text-text-primary transition-colors text-xs"
            @click="showSettings = false"
          >
            ✕
          </button>
        </div>
        <ChatSettingsPanel v-model="chatSettings" :selected-model="selectedModel" v-model:rag-enabled="ragEnabled" />
      </div>
    </div>
  </div>
</template>
