<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { Download } from 'lucide-vue-next'
import { useSessionStore } from '@/stores/session-store'
import { useMetricsStore } from '@/stores/metrics-store'
import { useTokenStore } from '@/stores/token-store'
import { downloadJson, downloadCsv, downloadMarkdown } from '@/utils/download'
import type { ToolCallEntry } from '@/types/toolcall'
import TabBar from '@/components/common/TabBar.vue'
import StatusBadge from '@/components/common/StatusBadge.vue'
import TokenStreamDisplay from '@/components/token-stream/TokenStreamDisplay.vue'
import MetricsDashboard from '@/components/metrics/MetricsDashboard.vue'
import ReasoningViewer from '@/components/reasoning/ReasoningViewer.vue'
import IntrospectionPanel from '@/components/introspection/IntrospectionPanel.vue'
import ToolCallTimeline from '@/components/tool-calls/ToolCallTimeline.vue'
import AgentGraphView from '@/components/agent-graph/AgentGraphView.vue'
import PromptInspector from '@/components/prompt-anatomy/PromptInspector.vue'
import ResponseOptimizerDrawer from '@/components/tool-optimizer/ResponseOptimizerDrawer.vue'

const props = defineProps<{ id: string }>()

const sessionStore = useSessionStore()
const metricsStore = useMetricsStore()
const tokenStore = useTokenStore()
const { t } = useI18n()

const activeTab = ref('stream')
const showExportMenu = ref(false)

function exportSessionJson() {
  const s = session.value
  if (!s) return
  const data = {
    session: s,
    metrics: metrics.value,
    tokens: tokenStore.getTokens(props.id),
  }
  downloadJson(data, `session-${s.id.slice(0, 8)}.json`)
  showExportMenu.value = false
}

function exportSessionMarkdown() {
  const s = session.value
  if (!s) return
  const m = metrics.value
  const lines: string[] = [
    `# Session Report — LLMxRay`,
    '',
    `**Model:** ${s.model}`,
    `**Session ID:** ${s.id}`,
    `**Status:** ${s.status}`,
    `**Created:** ${new Date(s.createdAt).toLocaleString()}`,
  ]
  if (m) {
    lines.push('')
    lines.push(`## Metrics`)
    lines.push('')
    if (m.tokensPerSecond) lines.push(`- **Speed:** ${m.tokensPerSecond.toFixed(1)} tok/s`)
    if (m.ttftMs) lines.push(`- **TTFT:** ${m.ttftMs.toFixed(0)} ms`)
    if (m.completionTokenCount) lines.push(`- **Tokens generated:** ${m.completionTokenCount}`)
    if (m.promptTokenCount) lines.push(`- **Prompt tokens:** ${m.promptTokenCount}`)
  }
  if (s.prompt) {
    lines.push('')
    lines.push(`## Prompt`)
    lines.push('')
    lines.push(s.prompt)
  }
  if (s.outputText) {
    lines.push('')
    lines.push(`## Response`)
    lines.push('')
    lines.push(s.outputText)
  }
  lines.push('')
  lines.push(`---`)
  lines.push(`*Generated by LLMxRay — Local LLM Observatory*`)
  downloadMarkdown(lines.join('\n'), `session-${s.id.slice(0, 8)}.md`)
  showExportMenu.value = false
}

function exportTokenStreamCsv() {
  const tokens = tokenStore.getTokens(props.id)
  if (tokens.length === 0) return
  const headers = ['Index', 'Token', 'Timestamp', 'Confidence', 'Logprob', 'InterTokenLatencyMs']
  const rows = tokens.map((tok) => [
    String(tok.index),
    tok.text,
    String(tok.timestamp),
    String(tok.confidence),
    String(tok.logprob ?? ''),
    String(tok.interTokenLatencyMs),
  ])
  downloadCsv(headers, rows, `token-stream-${props.id.slice(0, 8)}.csv`)
  showExportMenu.value = false
}

const tabs = computed(() => [
  { key: 'stream', label: t('session.tabs.stream') },
  { key: 'reasoning', label: t('session.tabs.reasoning') },
  { key: 'introspection', label: t('session.tabs.introspection') },
  { key: 'tools', label: t('session.tabs.tools') },
  { key: 'agent', label: t('session.tabs.agent') },
  { key: 'prompt', label: t('session.tabs.prompt') },
])


const session = computed(() => sessionStore.sessionById(props.id) ?? null)
const metrics = computed(() => metricsStore.getMetrics(props.id))

const optimizerEntry = ref<ToolCallEntry | null>(null)

onMounted(() => {
  sessionStore.setActiveSession(props.id)
})
</script>

<template>
  <div v-if="session" class="space-y-4">
    <div class="flex items-center justify-between">
      <div class="flex items-center gap-3">
        <h2 class="text-lg font-semibold">{{ session.model }}</h2>
        <StatusBadge :status="session.status" />
      </div>
      <div class="text-xs text-text-muted">{{ $t('session.sessionId', { id: session.id.slice(0, 8) }) }}</div>
    </div>

    <div class="flex items-center justify-between">
      <TabBar :tabs="tabs" :active-tab="activeTab" @update:active-tab="activeTab = $event" />
      <!-- Export dropdown -->
      <div class="relative">
        <button
          class="flex items-center gap-1 rounded-lg border border-border-default px-2.5 py-1 text-xs text-text-secondary hover:text-text-primary transition-colors"
          @click="showExportMenu = !showExportMenu"
        >
          <Download class="h-3.5 w-3.5" />
          {{ $t('session.export.title') }}
        </button>
        <div v-if="showExportMenu" class="fixed inset-0 z-10" @click="showExportMenu = false" />
        <div
          v-if="showExportMenu"
          class="absolute end-0 top-full z-20 mt-1 w-56 rounded-lg border border-border-default bg-surface-raised shadow-lg py-1"
        >
          <button class="w-full px-3 py-2 text-start text-xs text-text-secondary hover:bg-surface-overlay" @click="exportSessionJson">
            {{ $t('session.export.downloadJson') }}
          </button>
          <button class="w-full px-3 py-2 text-start text-xs text-text-secondary hover:bg-surface-overlay" @click="exportSessionMarkdown">
            {{ $t('session.export.downloadMarkdown') }}
          </button>
          <button class="w-full px-3 py-2 text-start text-xs text-text-secondary hover:bg-surface-overlay" @click="exportTokenStreamCsv">
            {{ $t('session.export.downloadTokenCsv') }}
          </button>
        </div>
      </div>
    </div>

    <div class="mt-4">
      <template v-if="activeTab === 'stream'">
        <div class="space-y-4">
          <TokenStreamDisplay :session-id="id" />
          <MetricsDashboard :metrics="metrics" />
        </div>
      </template>

      <template v-else-if="activeTab === 'reasoning'">
        <ReasoningViewer :session-id="id" />
      </template>

      <template v-else-if="activeTab === 'introspection'">
        <IntrospectionPanel :session-id="id" :model-name="session.model" />
      </template>

      <template v-else-if="activeTab === 'tools'">
        <ToolCallTimeline :session-id="id" @optimize="optimizerEntry = $event" />
      </template>

      <template v-else-if="activeTab === 'agent'">
        <AgentGraphView :session-id="id" />
      </template>

      <template v-else-if="activeTab === 'prompt'">
        <PromptInspector :session-id="id" />
      </template>
    </div>
  </div>

  <div v-else class="flex items-center justify-center py-20 text-text-muted">
    {{ $t('session.notFound') }}
  </div>

  <ResponseOptimizerDrawer
    v-if="optimizerEntry"
    :entry="optimizerEntry"
    @close="optimizerEntry = null"
  />
</template>
