import type { ComparisonRun } from '@/types/comparison'
import type { SessionMetrics } from '@/types/metrics'
import { LANGUAGE_NAMES } from '@/utils/slot-labels'

function formatDate(ts: number): string {
  return new Date(ts).toISOString().split('T')[0] ?? ''
}

function getMetrics(run: ComparisonRun, slotId: string): SessionMetrics | null {
  return run.executions.find(e => e.slotId === slotId)?.metrics ?? null
}

export function buildMarkdownReport(
  run: ComparisonRun,
  metricsGetter?: (sessionId: string) => SessionMetrics | null,
  commentary?: string,
): string {
  const models = [...new Set(run.executions.map(e => e.model))]
  const hasLanguages = run.executions.some(e => e.language)
  const lines: string[] = []

  // Title
  if (hasLanguages) {
    const langs = run.executions.filter(e => e.language).map(e => e.language!.toUpperCase()).join(' vs ')
    lines.push(`# Language Compare: ${langs} — LLMxRay`)
  } else {
    lines.push(`# Model Comparison — LLMxRay`)
  }
  lines.push('')
  lines.push(`**Date:** ${formatDate(run.createdAt)}`)
  lines.push(`**Model${models.length > 1 ? 's' : ''}:** ${models.join(', ')}`)
  lines.push('')

  // User commentary
  if (commentary?.trim()) {
    lines.push(commentary.trim())
    lines.push('')
    lines.push('---')
    lines.push('')
  }

  // Prompts
  if (hasLanguages) {
    lines.push('## Prompts')
    lines.push('')
    lines.push('| Language | Text |')
    lines.push('|----------|------|')

    // Find min prompt tokens for ratio
    const promptTokens = run.executions.map(e => {
      const m = metricsGetter ? metricsGetter(e.sessionId) : getMetrics(run, e.slotId)
      return m?.promptTokenCount ?? 0
    })
    const minTokens = Math.min(...promptTokens.filter(t => t > 0)) || 1

    for (const exec of run.executions) {
      const lang = exec.language ? (LANGUAGE_NAMES[exec.language] ?? exec.language) : exec.label
      const prompt = (exec.effectivePrompt ?? run.prompt).slice(0, 100)
      const m = metricsGetter ? metricsGetter(exec.sessionId) : getMetrics(run, exec.slotId)
      const tokens = m?.promptTokenCount ?? 0
      const ratio = tokens > 0 ? (tokens / minTokens).toFixed(1) : '?'
      lines.push(`| ${lang} | ${prompt}${(exec.effectivePrompt ?? run.prompt).length > 100 ? '...' : ''} (${tokens} tokens, ${ratio}x) |`)
    }
    lines.push('')
  } else {
    lines.push('## Prompt')
    lines.push('')
    lines.push(`> ${run.prompt.slice(0, 200)}${run.prompt.length > 200 ? '...' : ''}`)
    lines.push('')
  }

  // Results
  lines.push('## Results')
  lines.push('')
  lines.push('| Slot | TTFT | Speed | Tokens | Prompt Tokens |')
  lines.push('|------|------|-------|--------|---------------|')

  for (const exec of run.executions) {
    if (exec.status !== 'completed') continue
    const m = metricsGetter ? metricsGetter(exec.sessionId) : exec.metrics
    const label = exec.language ? (LANGUAGE_NAMES[exec.language] ?? exec.language) : exec.label
    const ttft = m ? `${Math.round(m.ttftMs)}ms` : '-'
    const speed = m ? `${m.tokensPerSecond.toFixed(1)} tok/s` : '-'
    const tokens = m?.completionTokenCount ?? '-'
    const prompt = m?.promptTokenCount ?? '-'
    lines.push(`| ${label} | ${ttft} | ${speed} | ${tokens} | ${prompt} |`)
  }
  lines.push('')

  // Token Tax
  if (hasLanguages) {
    const completed = run.executions.filter(e => e.status === 'completed')
    const tokenCounts = completed.map(e => {
      const m = metricsGetter ? metricsGetter(e.sessionId) : e.metrics
      return { lang: e.language ?? 'unknown', tokens: m?.promptTokenCount ?? 0 }
    }).filter(t => t.tokens > 0)

    if (tokenCounts.length >= 2) {
      const min = Math.min(...tokenCounts.map(t => t.tokens))
      lines.push('## Token Tax')
      lines.push('')
      for (const t of tokenCounts) {
        const ratio = (t.tokens / min).toFixed(1)
        const lang = LANGUAGE_NAMES[t.lang] ?? t.lang
        if (t.tokens === min) {
          lines.push(`- **${lang}**: ${t.tokens} tokens (baseline)`)
        } else {
          lines.push(`- **${lang}**: ${t.tokens} tokens (${ratio}x)`)
        }
      }
      lines.push('')
    }
  }

  lines.push('---')
  lines.push('*Generated by [LLMxRay](https://lognebudo.github.io/llmxray/) — Local LLM Observatory*')

  return lines.join('\n')
}

export function buildDiscussionUrl(run: ComparisonRun, metricsGetter?: (sessionId: string) => SessionMetrics | null, commentary?: string): string {
  const hasLanguages = run.executions.some(e => e.language)
  const models = [...new Set(run.executions.map(e => e.model))]

  let title: string
  if (hasLanguages) {
    const langs = run.executions.filter(e => e.language).map(e => e.language!.toUpperCase()).join(' vs ')
    title = `Language Compare: ${langs} — ${models[0]}`
  } else {
    title = `Model Comparison: ${models.join(' vs ')}`
  }

  const body = buildMarkdownReport(run, metricsGetter, commentary)

  return `https://github.com/LogneBudo/llmxray/discussions/new?category=show-and-tell&title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function exportAsJson(run: ComparisonRun): void {
  const data = JSON.stringify(run, null, 2)
  downloadFile(data, `llmxray-compare-${run.id}.json`, 'application/json')
}

export function exportAsMarkdown(run: ComparisonRun, metricsGetter?: (sessionId: string) => SessionMetrics | null): void {
  const md = buildMarkdownReport(run, metricsGetter)
  downloadFile(md, `llmxray-compare-${run.id}.md`, 'text/markdown')
}
