import type { SessionMetrics } from '@/types/metrics'
import type { StreamToken } from '@/types/token'
import { downloadJson, downloadCsv, downloadMarkdown } from '@/utils/download'

export interface SessionExportData {
  id: string
  model: string
  prompt: string
  outputText: string
  metrics: SessionMetrics | null
  status: string
  createdAt?: number
}

/**
 * Export session data as a JSON file.
 */
export function exportSessionAsJson(sessionData: SessionExportData): void {
  const filename = `session-${sessionData.model}-${sessionData.id}.json`
  downloadJson(sessionData, filename)
}

/**
 * Export session data as a formatted Markdown report.
 */
export function exportSessionAsMarkdown(sessionData: SessionExportData): void {
  const date = sessionData.createdAt
    ? new Date(sessionData.createdAt).toLocaleString()
    : 'N/A'

  const m = sessionData.metrics

  const metricsRows = m
    ? [
        `| TTFT | ${m.ttftMs.toFixed(0)}ms |`,
        `| Speed | ${m.tokensPerSecond.toFixed(1)} tok/s |`,
        `| Prompt Tokens | ${m.promptTokenCount} |`,
        `| Completion Tokens | ${m.completionTokenCount} |`,
        `| Total Duration | ${m.totalDurationMs.toFixed(0)}ms |`,
      ].join('\n')
    : '| N/A | No metrics available |'

  const md = `# Session Report — LLMxRay

**Model:** ${sessionData.model}
**Date:** ${date}
**Status:** ${sessionData.status}

## Prompt
> ${sessionData.prompt.replace(/\n/g, '\n> ')}

## Response
${sessionData.outputText}

## Performance Metrics

| Metric | Value |
|--------|-------|
${metricsRows}

---
*Generated by LLMxRay*
`

  const filename = `session-report-${sessionData.model}-${sessionData.id}.md`
  downloadMarkdown(md, filename)
}

/**
 * Export a token stream as a CSV file with one row per token.
 */
export function exportTokenStreamAsCsv(tokens: StreamToken[], sessionId: string): void {
  const headers = [
    'Index',
    'Text',
    'Confidence',
    'Logprob',
    'Latency (ms)',
    'Timestamp',
  ]

  const rows = tokens.map((t) => [
    t.index.toString(),
    t.text,
    (t.confidence * 100).toFixed(1) + '%',
    t.logprob !== undefined ? t.logprob.toFixed(4) : '',
    t.interTokenLatencyMs.toFixed(0),
    new Date(t.timestamp).toISOString(),
  ])

  const filename = `token-stream-${sessionId}.csv`
  downloadCsv(headers, rows, filename)
}
